/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ar-models`; params?: Router.UnknownInputParams; } | { pathname: `/ar-viewer`; params?: Router.UnknownInputParams; } | { pathname: `/finder`; params?: Router.UnknownInputParams; } | { pathname: `/lingo-island`; params?: Router.UnknownInputParams; } | { pathname: `/practice`; params?: Router.UnknownInputParams; } | { pathname: `/redeem`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/vocab_levels`; params?: Router.UnknownInputParams; } | { pathname: `/vocab_list`; params?: Router.UnknownInputParams; } | { pathname: `/vocab_test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/ar-models`; params?: Router.UnknownOutputParams; } | { pathname: `/ar-viewer`; params?: Router.UnknownOutputParams; } | { pathname: `/finder`; params?: Router.UnknownOutputParams; } | { pathname: `/lingo-island`; params?: Router.UnknownOutputParams; } | { pathname: `/practice`; params?: Router.UnknownOutputParams; } | { pathname: `/redeem`; params?: Router.UnknownOutputParams; } | { pathname: `/result`; params?: Router.UnknownOutputParams; } | { pathname: `/vocab_levels`; params?: Router.UnknownOutputParams; } | { pathname: `/vocab_list`; params?: Router.UnknownOutputParams; } | { pathname: `/vocab_test`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/camera` | `/camera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/ar-models${`?${string}` | `#${string}` | ''}` | `/ar-viewer${`?${string}` | `#${string}` | ''}` | `/finder${`?${string}` | `#${string}` | ''}` | `/lingo-island${`?${string}` | `#${string}` | ''}` | `/practice${`?${string}` | `#${string}` | ''}` | `/redeem${`?${string}` | `#${string}` | ''}` | `/result${`?${string}` | `#${string}` | ''}` | `/vocab_levels${`?${string}` | `#${string}` | ''}` | `/vocab_list${`?${string}` | `#${string}` | ''}` | `/vocab_test${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/camera${`?${string}` | `#${string}` | ''}` | `/camera${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/ar-models`; params?: Router.UnknownInputParams; } | { pathname: `/ar-viewer`; params?: Router.UnknownInputParams; } | { pathname: `/finder`; params?: Router.UnknownInputParams; } | { pathname: `/lingo-island`; params?: Router.UnknownInputParams; } | { pathname: `/practice`; params?: Router.UnknownInputParams; } | { pathname: `/redeem`; params?: Router.UnknownInputParams; } | { pathname: `/result`; params?: Router.UnknownInputParams; } | { pathname: `/vocab_levels`; params?: Router.UnknownInputParams; } | { pathname: `/vocab_list`; params?: Router.UnknownInputParams; } | { pathname: `/vocab_test`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/camera` | `/camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
